services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - my-app-network

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my-app-network

  client:
    image: curlimages/curl:latest
    command: ["sleep", "infinity"]  # Keep container running
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge