version: '3.8'

services:
  dns:
    image: debian/bind9
    container_name: bind9
    build:
      context: ./DNS
      dockerfile: Dockerfile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./DNS/named.conf.local:/etc/bind/named.conf.local
      - ./DNS/db.asa.br:/etc/bind/zones/db.asa.br
    networks:
      - asa-network

  web:
    image: httpd:slim
    container_name: web-server
    build:
      context: ./WEB
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./WEB/index.html:/usr/local/apache2/htdocs/index.html
    networks:
      - asa-network
    depends_on:
      - dns

networks:
  asa-network:
    driver: bridge
