#Docker Networks
networks:
  asa-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
    attachable: true

services:
  dns:
    build: 
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
    networks:
      asa-network:
        ipv4_address: 172.25.0.2

  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
    depends_on:
      - web1
      - web2
    networks:
      asa-network:
        ipv4_address: 172.25.0.3

  web1:
    build: 
      context: ./web1
      dockerfile: Dockerfile
    container_name: web1
    networks:
      asa-network:
        ipv4_address: 172.25.0.4

  web2:
    build: 
      context: ./web2
      dockerfile: Dockerfile
    container_name: web2
    networks:
      asa-network:
        ipv4_address: 172.25.0.5
